
services:
  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb+srv://root:1q2w3e4r@mongodbhosting.5unov.mongodb.net/?retryWrites=true&w=majority&appName=mongoDBhosting

  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: